=== ClaudiaYLopezLafita/LMSGI-21-22/Unidad 01/EJER_CLASE/EJER_DTD/Ejer_curso.dtd
<!ELEMENT curso (asignatura+)>
<!ELEMENT asignatura ((nombre_asignatura | codigo), alumnos?, profesor?)>
<!ELEMENT nombre_asignatura (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombre, apellido)>
<!ELEMENT profesor (nombre, apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>

=== ClaudiaYLopezLafita/LMSGI-21-22/Unidad 01/EJER_CLASE/ACTV_CLASES/EJER_DTD/Ejer_curso.xml
<?xml version ="1.0" encoding="UTF-8"?>

<!-- Ejercicio 1: se quiere montar una BD de un curso donde se guardan
    las asignaturas, de ellas guardamos su nombre, los alumnos que toman 
    esa asignatura y el profesor que la imparte, de los alumnos y profesor
    queremos guardar su nonmbre y apellido-->

<!DOCTYPE curso SYSTEM "Ejer_curso.dtd">

<curso>
    <asignatura>
        <nombre_asignatura> Matematicas </nombre_asignatura>

        <alumnos>
            <alumno>
                <nombre> Manuel </nombre>
                <apellido> Gómez </apellido>
            </alumno>

            <alumno>
                <nombre> Pilar </nombre>
                <apellido> Dorado </apellido>
            </alumno>
        </alumnos>

        <profesor>
            <nombre> Juan </nombre>
            <apellido> López </apellido>
        </profesor>

    </asignatura>

    <asignatura>
        <codigo> BLG4500 </codigo>
        <alumnos>
            <alumno>
                <nombre> Teresa </nombre>
                <apellido> Lafita </apellido>
            </alumno>

            <alumno>
                <nombre> Claudia </nombre>
                <apellido> Lafita </apellido>
            </alumno>
        </alumnos>
        <profesor>
            <nombre> Miguel </nombre>
            <apellido> Campos </apellido>
        </profesor>
    </asignatura>
</curso>
