<?xml version="1.0" encoding="UTF-8"?>

<!-- Escribir la DTD que permita validar el documento XML que se muestra a continuación. Hacer dos
versiones en cada caso: DTD interna.-->

<!DOCTYPE lista_personas [
<!ELEMENT lista_personas (persona+)>
<!ELEMENT persona (nombre, fecha_nacimiento,sexo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
]>

<lista_personas>
    <persona>
        <nombre>Antonio Moreno</nombre>
        <fecha_nacimiento>27-11-2008</fecha_nacimiento>
        <sexo>Varón</sexo>
    </persona>
</lista_personas>